services:
  database:
    image: shubhanshu1902/spe_database
    build: ./Database
    container_name: database
    restart: always
    ports:
      - "3306:3306"
    networks:
      - spring_net

    volumes:
      - mysql-data:/var/lib/mysql


  backend: 
    image: shubhanshu1902/spe_backend
    depends_on:
      - database
    build: ./backend
    restart: on-failure
    ports:
      - "8070:8070"
    environment:
      - spring.datasource.url=jdbc:mysql://database:3306/UserManagement?allowPublicKeyRetrieval=true
    networks:
      - spring_net
      - frontend_net
    
    
  frontend:
    image: shubhanshu1902/spe_frontend
    build: ./frontend
    ports:
      - 3000:3000
    networks:
      - frontend_net

networks:
  spring_net:
  frontend_net:

volumes:
  mysql-data:
